[package]
name = "yank"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
preferences = "2.0.0"
serde = { version = "1.0.219", features = ["derive"] }
